[2024-08-29T19:47:50.483+0000] {processor.py:157} INFO - Started process (PID=48872) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:47:50.484+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:47:50.484+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:47:50.484+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:47:50.487+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:47:50.486+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:47:50.487+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:47:50.487+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:47:50.487+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:47:50.496+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:48:41.184+0000] {processor.py:157} INFO - Started process (PID=49374) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:48:41.185+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:48:41.185+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:48:41.185+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:48:41.189+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:48:41.189+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:48:41.190+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:48:41.190+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:48:41.190+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:48:41.199+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-08-29T19:49:28.018+0000] {processor.py:157} INFO - Started process (PID=49640) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:49:28.019+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:49:28.019+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:49:28.019+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:49:28.022+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:49:28.021+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:49:28.022+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:49:28.022+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:49:28.022+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:49:28.031+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T19:50:16.434+0000] {processor.py:157} INFO - Started process (PID=49800) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:50:16.434+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:50:16.435+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:50:16.435+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:50:16.438+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:50:16.437+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:50:16.438+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:50:16.438+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:50:16.438+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:50:16.447+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:51:02.194+0000] {processor.py:157} INFO - Started process (PID=50490) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:02.194+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:51:02.195+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:02.195+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:02.197+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:02.197+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:51:02.198+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:02.198+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:51:02.198+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:02.207+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:51:51.113+0000] {processor.py:157} INFO - Started process (PID=50858) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:51.114+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:51:51.114+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:51.114+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:51.117+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:51.116+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:51:51.117+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:51:51.117+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:51:51.118+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:51:51.127+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-08-29T19:52:37.689+0000] {processor.py:157} INFO - Started process (PID=50962) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:52:37.690+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:52:37.691+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:52:37.691+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:52:37.693+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:52:37.693+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:52:37.694+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:52:37.694+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:52:37.694+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:52:37.702+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:53:21.644+0000] {processor.py:157} INFO - Started process (PID=51060) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:53:21.645+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:53:21.646+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:53:21.646+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:53:21.648+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:53:21.648+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:53:21.649+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:53:21.648+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:53:21.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:53:21.657+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:54:06.992+0000] {processor.py:157} INFO - Started process (PID=51187) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:06.993+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:54:06.994+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:06.994+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:06.997+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:06.996+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:54:06.997+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:06.997+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:54:06.997+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:07.005+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T19:54:53.342+0000] {processor.py:157} INFO - Started process (PID=51445) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:53.343+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:54:53.344+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:53.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:53.346+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:53.346+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:54:53.346+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:54:53.346+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:54:53.347+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:54:53.355+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T19:55:41.140+0000] {processor.py:157} INFO - Started process (PID=51794) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:55:41.141+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T19:55:41.141+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:55:41.141+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:55:41.144+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:55:41.143+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T19:55:41.144+0000] {logging_mixin.py:149} INFO - [2024-08-29T19:55:41.144+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T19:55:41.144+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T19:55:41.154+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:11:44.717+0000] {processor.py:157} INFO - Started process (PID=56382) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:11:44.717+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:11:44.718+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:11:44.718+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:11:44.721+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:11:44.720+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:11:44.721+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:11:44.721+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:11:44.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:11:44.729+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:12:30.076+0000] {processor.py:157} INFO - Started process (PID=56672) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:12:30.077+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:12:30.077+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:12:30.077+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:12:30.080+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:12:30.079+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:12:30.080+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:12:30.080+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:12:30.080+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:12:30.089+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:13:14.449+0000] {processor.py:157} INFO - Started process (PID=56884) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:13:14.450+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:13:14.450+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:13:14.450+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:13:14.453+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:13:14.452+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:13:14.453+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:13:14.453+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:13:14.453+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:13:14.461+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:15:12.019+0000] {processor.py:157} INFO - Started process (PID=57446) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:12.020+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:15:12.021+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:12.021+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:12.023+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:12.023+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:15:12.023+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:12.023+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:15:12.024+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:12.032+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:15:57.454+0000] {processor.py:157} INFO - Started process (PID=57946) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:57.455+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:15:57.455+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:57.455+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:57.458+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:57.457+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:15:57.458+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:15:57.458+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:15:57.458+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:15:57.467+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:24:05.106+0000] {processor.py:157} INFO - Started process (PID=61014) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:24:05.107+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:24:05.108+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:24:05.108+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:24:05.110+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:24:05.110+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:24:05.110+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:24:05.110+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:24:05.111+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:24:05.119+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:26:00.837+0000] {processor.py:157} INFO - Started process (PID=62470) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:00.838+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:26:00.838+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:00.838+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:00.841+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:00.840+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:26:00.841+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:00.841+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:26:00.841+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:00.850+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:26:54.699+0000] {processor.py:157} INFO - Started process (PID=63165) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:54.700+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:26:54.701+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:54.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:54.703+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:54.702+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:26:54.703+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:26:54.703+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:26:54.704+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:26:54.713+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-08-29T20:27:38.822+0000] {processor.py:157} INFO - Started process (PID=63524) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:27:38.822+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:27:38.823+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:27:38.823+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:27:38.825+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:27:38.825+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:27:38.826+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:27:38.825+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:27:38.826+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:27:38.834+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:28:23.061+0000] {processor.py:157} INFO - Started process (PID=63598) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:28:23.062+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:28:23.063+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:28:23.062+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:28:23.065+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:28:23.064+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:28:23.065+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:28:23.065+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:28:23.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:28:23.073+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:29:55.310+0000] {processor.py:157} INFO - Started process (PID=64806) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:29:55.311+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:29:55.311+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:29:55.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:29:55.314+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:29:55.313+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:29:55.314+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:29:55.314+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:29:55.314+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:29:55.322+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-08-29T20:31:05.850+0000] {processor.py:157} INFO - Started process (PID=65477) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:31:05.850+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:31:05.851+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:31:05.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:31:05.853+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:31:05.853+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:31:05.854+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:31:05.854+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:31:05.854+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:31:05.862+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:32:56.291+0000] {processor.py:157} INFO - Started process (PID=66845) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:32:56.292+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:32:56.293+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:32:56.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:32:56.295+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:32:56.294+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:32:56.295+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:32:56.295+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:32:56.295+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:32:56.304+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:34:20.444+0000] {processor.py:157} INFO - Started process (PID=67938) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:34:20.445+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:34:20.446+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:34:20.446+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:34:20.448+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:34:20.448+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:34:20.448+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:34:20.448+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:34:20.449+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:34:20.457+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:35:33.679+0000] {processor.py:157} INFO - Started process (PID=68884) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:35:33.680+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:35:33.680+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:35:33.680+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:35:33.683+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:35:33.682+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:35:33.683+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:35:33.683+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:35:33.683+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:35:33.692+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:37:27.047+0000] {processor.py:157} INFO - Started process (PID=70274) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:37:27.048+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:37:27.048+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:37:27.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:37:27.050+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:37:27.050+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:37:27.051+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:37:27.051+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:37:27.051+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:37:27.059+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-08-29T20:38:52.627+0000] {processor.py:157} INFO - Started process (PID=71452) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:38:52.628+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-29T20:38:52.628+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:38:52.628+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:38:52.631+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:38:52.630+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-29T20:38:52.631+0000] {logging_mixin.py:149} INFO - [2024-08-29T20:38:52.631+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-29T20:38:52.631+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-29T20:38:52.639+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
