[2024-09-03T10:58:10.042+0000] {processor.py:157} INFO - Started process (PID=3480) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:10.043+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T10:58:10.043+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:10.043+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:10.046+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:10.045+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T10:58:10.046+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:10.046+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T10:58:10.046+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:10.055+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-09-03T10:58:55.600+0000] {processor.py:157} INFO - Started process (PID=3771) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:55.600+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T10:58:55.601+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:55.601+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:55.603+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:55.603+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T10:58:55.604+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:58:55.604+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T10:58:55.604+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:58:55.612+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-09-03T10:59:41.988+0000] {processor.py:157} INFO - Started process (PID=3872) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:59:41.988+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T10:59:41.989+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:59:41.989+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:59:41.991+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:59:41.991+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T10:59:41.992+0000] {logging_mixin.py:149} INFO - [2024-09-03T10:59:41.992+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T10:59:41.992+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T10:59:42.000+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-09-03T11:00:25.068+0000] {processor.py:157} INFO - Started process (PID=4305) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:00:25.069+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:00:25.069+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:00:25.069+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:00:25.072+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:00:25.072+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:00:25.072+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:00:25.072+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:00:25.073+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:00:25.082+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:01:12.042+0000] {processor.py:157} INFO - Started process (PID=4654) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:12.043+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:01:12.044+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:12.044+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:12.046+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:12.046+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:01:12.046+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:12.046+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:01:12.047+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:12.056+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:01:58.674+0000] {processor.py:157} INFO - Started process (PID=4789) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:58.674+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:01:58.675+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:58.675+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:58.678+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:58.677+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:01:58.678+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:01:58.678+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:01:58.678+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:01:58.687+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:02:45.826+0000] {processor.py:157} INFO - Started process (PID=4929) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:02:45.827+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:02:45.827+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:02:45.827+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:02:45.830+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:02:45.829+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:02:45.830+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:02:45.830+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:02:45.830+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:02:45.839+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:04:03.561+0000] {processor.py:157} INFO - Started process (PID=5662) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:04:03.562+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:04:03.562+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:04:03.562+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:04:03.565+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:04:03.564+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:04:03.565+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:04:03.565+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:04:03.565+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:04:03.575+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:07:12.482+0000] {processor.py:157} INFO - Started process (PID=7218) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:07:12.483+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:07:12.483+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:07:12.483+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:07:12.486+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:07:12.485+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:07:12.486+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:07:12.486+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:07:12.486+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:07:12.495+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-09-03T11:09:17.026+0000] {processor.py:157} INFO - Started process (PID=8086) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:09:17.027+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:09:17.028+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:09:17.028+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:09:17.031+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:09:17.030+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:09:17.031+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:09:17.031+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:09:17.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:09:17.040+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:11:22.318+0000] {processor.py:157} INFO - Started process (PID=8938) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:11:22.319+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:11:22.320+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:11:22.320+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:11:22.323+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:11:22.322+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:11:22.323+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:11:22.323+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:11:22.323+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:11:22.332+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:13:31.419+0000] {processor.py:157} INFO - Started process (PID=9863) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:13:31.420+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:13:31.421+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:13:31.420+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:13:31.423+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:13:31.423+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:13:31.423+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:13:31.423+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:13:31.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:13:31.433+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:15:37.414+0000] {processor.py:157} INFO - Started process (PID=10914) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:15:37.415+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:15:37.416+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:15:37.416+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:15:37.418+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:15:37.418+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:15:37.419+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:15:37.419+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:15:37.419+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:15:37.428+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:17:51.417+0000] {processor.py:157} INFO - Started process (PID=12087) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:17:51.418+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:17:51.418+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:17:51.418+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:17:51.420+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:17:51.420+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:17:51.421+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:17:51.421+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:17:51.421+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:17:51.429+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-09-03T11:20:34.440+0000] {processor.py:157} INFO - Started process (PID=13588) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:20:34.441+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:20:34.441+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:20:34.441+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:20:34.444+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:20:34.444+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:20:34.444+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:20:34.444+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:20:34.445+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:20:34.454+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:23:30.626+0000] {processor.py:157} INFO - Started process (PID=15021) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:23:30.627+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:23:30.627+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:23:30.627+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:23:30.630+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:23:30.629+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:23:30.630+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:23:30.630+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:23:30.630+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:23:30.639+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:26:21.382+0000] {processor.py:157} INFO - Started process (PID=16208) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:26:21.383+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:26:21.384+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:26:21.384+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:26:21.387+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:26:21.386+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:26:21.387+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:26:21.387+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:26:21.387+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:26:21.397+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:29:23.909+0000] {processor.py:157} INFO - Started process (PID=17630) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:29:23.909+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:29:23.910+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:29:23.910+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:29:23.913+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:29:23.912+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:29:23.913+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:29:23.913+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:29:23.913+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:29:23.922+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:33:37.376+0000] {processor.py:157} INFO - Started process (PID=20111) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:33:37.377+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:33:37.378+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:33:37.378+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:33:37.381+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:33:37.380+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:33:37.381+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:33:37.381+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:33:37.381+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:33:37.391+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-03T11:37:11.359+0000] {processor.py:157} INFO - Started process (PID=22525) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:11.360+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:37:11.361+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:11.361+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:11.364+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:11.363+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:37:11.364+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:11.364+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:37:11.364+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:11.375+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-09-03T11:37:59.313+0000] {processor.py:157} INFO - Started process (PID=22752) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:59.314+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:37:59.315+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:59.315+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:59.317+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:59.317+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:37:59.318+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:37:59.318+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:37:59.318+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:37:59.327+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:38:43.108+0000] {processor.py:157} INFO - Started process (PID=22974) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:38:43.109+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:38:43.110+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:38:43.110+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:38:43.113+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:38:43.112+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:38:43.113+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:38:43.113+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:38:43.113+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:38:43.122+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:39:32.068+0000] {processor.py:157} INFO - Started process (PID=23208) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:39:32.069+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:39:32.070+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:39:32.070+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:39:32.073+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:39:32.072+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:39:32.073+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:39:32.073+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:39:32.073+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:39:32.082+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:40:45.125+0000] {processor.py:157} INFO - Started process (PID=23765) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:40:45.125+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:40:45.126+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:40:45.126+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:40:45.129+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:40:45.128+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:40:45.129+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:40:45.129+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:40:45.129+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:40:45.138+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:43:20.107+0000] {processor.py:157} INFO - Started process (PID=25644) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:43:20.108+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:43:20.109+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:43:20.108+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:43:20.111+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:43:20.111+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:43:20.111+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:43:20.111+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:43:20.112+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:43:20.121+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:47:18.203+0000] {processor.py:157} INFO - Started process (PID=27572) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:47:18.203+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:47:18.204+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:47:18.204+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:47:18.207+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:47:18.206+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:47:18.207+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:47:18.207+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:47:18.207+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:47:18.216+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:50:15.640+0000] {processor.py:157} INFO - Started process (PID=29590) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:50:15.641+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:50:15.642+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:50:15.641+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:50:15.644+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:50:15.644+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:50:15.648+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:50:15.644+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:50:15.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:50:15.678+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-09-03T11:51:00.803+0000] {processor.py:157} INFO - Started process (PID=29694) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:00.804+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:51:00.804+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:00.804+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:00.807+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:00.806+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:51:00.807+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:00.807+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:51:00.807+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:00.817+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:51:44.612+0000] {processor.py:157} INFO - Started process (PID=29742) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:44.613+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:51:44.613+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:44.613+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:44.616+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:44.615+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:51:44.616+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:51:44.616+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:51:44.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:51:44.625+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-09-03T11:52:30.969+0000] {processor.py:157} INFO - Started process (PID=29790) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:52:30.970+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:52:30.970+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:52:30.970+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:52:30.973+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:52:30.972+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:52:30.973+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:52:30.973+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:52:30.973+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:52:30.982+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:53:17.502+0000] {processor.py:157} INFO - Started process (PID=29839) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:53:17.502+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:53:17.503+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:53:17.503+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:53:17.506+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:53:17.505+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:53:17.506+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:53:17.506+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:53:17.506+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:53:17.516+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:54:05.126+0000] {processor.py:157} INFO - Started process (PID=29915) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:05.126+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:54:05.127+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:05.127+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:05.130+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:05.129+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:54:05.130+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:05.130+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:54:05.130+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:05.140+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-09-03T11:54:55.204+0000] {processor.py:157} INFO - Started process (PID=29972) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:55.205+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:54:55.205+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:55.205+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:55.208+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:55.208+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:54:55.208+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:54:55.208+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:54:55.209+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:54:55.218+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:55:38.687+0000] {processor.py:157} INFO - Started process (PID=30020) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:55:38.688+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:55:38.689+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:55:38.689+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:55:38.691+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:55:38.691+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:55:38.691+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:55:38.691+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:55:38.692+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:55:38.701+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-09-03T11:56:27.530+0000] {processor.py:157} INFO - Started process (PID=30070) to work on /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:56:27.531+0000] {processor.py:826} INFO - Processing file /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-03T11:56:27.532+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:56:27.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:56:27.535+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:56:27.534+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-03T11:56:27.535+0000] {logging_mixin.py:149} INFO - [2024-09-03T11:56:27.535+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-03T11:56:27.535+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-03T11:56:27.545+0000] {processor.py:179} INFO - Processing /home/airflow-vm/data-engineer-batch-processing-financial-services/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
